<?= $this->extend('emails/layout') ?>

<?= $this->section('content') ?>
    <!-- ================= BODY ================= -->
    <div style="padding:40px; color:#333333;">

        <p style="margin-top:0; font-size:15px;">
            Good day <strong><?= esc($full_name ?? 'User') ?></strong>,
        </p>

        <p style="font-size:15px; line-height:1.7;">
            This is to formally notify you in your capacity as
            <strong><?= esc($position ?? 'User Position') ?></strong>
            of the <strong><?= esc($managed_unit_div_org ?? 'Managed Unit/Division/Organization') ?></strong>,
            that there are currently
            <strong style="color:#d32f2f;"><?= esc($pending_count ?? 0) ?></strong>
            pending travel order(s) requiring your immediate attention and action.
        </p>

        <p style="font-size:15px; line-height:1.7;">
            Kindly log in to the Travel Order Management System at your earliest convenience
            to review and process the pending requests under your supervision.
        </p>

        <!-- ================= BUTTON (CENTERED) ================= -->
        <div style="margin-top:30px; text-align:center;">
            <a href="#"
              style="display:inline-block; background:#1b5e20; color:#ffffff; text-decoration:none; padding:14px 28px; font-size:14px; font-weight:bold; border-radius:5px;">
                Open Travel Order System
            </a>
        </div>

        <hr style="border:none; border-top:1px solid #dee2e6; margin:35px 0;">

        <!-- ================= DISCLAIMER (CENTERED) ================= -->
        <div style="text-align:center; font-size:12px; color:#6c757d; line-height:1.6;">
            This is an automated notification generated by the Travel Order Management System of the Provincial Environment and Natural Resources Office (PENRO), DENR.
        </div>

    </div>

<?= $this->endSection() ?>
